name: CI
on:
  - pull_request
jobs:
  check-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json
        run: composer validate

  php-linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: PHP lint
        run: "find *.php Classes Configuration Tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"

  js-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and install node for npm
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install modules based on package-lock.json
        run: npm install
        working-directory: ./Build/Sources

      - name: Run ESLint
        run: npm run lint
        working-directory: ./Build/Sources

  coding-guideline:
    runs-on: ubuntu-latest
    needs:
      - php-linting
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Coding Guideline
        run: .build/bin/php-cs-fixer fix --config=Build/.php-cs-fixer.dist.php -v --dry-run --using-cache=no --path-mode=intersection ./

  code-quality:
    runs-on: ubuntu-latest
    needs:
      - php-linting
    strategy:
      matrix:
        include:
          - php-version: '8.1'
            typo3-version: '^12.4'
          - php-version: '8.2'
            typo3-version: '^12.4'
          - php-version: '8.3'
            typo3-version: '^12.4'
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Install dependencies with expected TYPO3 version
        run: |-
          composer require --no-interaction --prefer-dist --no-progress "typo3/cms-core:${{ matrix.typo3-version }}" "typo3/cms-extbase:${{ matrix.typo3-version }}" "typo3/cms-frontend:${{ matrix.typo3-version }}"

      - name: Code Quality (by PHPStan)
        run: .build/bin/phpstan analyse -c Build/phpstan.neon
